// frontend/src/pages/Home.tsx
import { useNavigate } from 'react-router-dom';
import { Button } from '../components/ui/Button';
import { Card } from '../components/ui/Card';
import './Home.css';

export function Home() {
  const navigate = useNavigate();

  return (
    <div className="home-container">
      <div className="home-content">
        <div className="home-header">
          <h1 className="home-title">🎬 Movie Night</h1>
          <p className="home-subtitle">
            Escolha filmes com amigos de forma democrática e aleatória
          </p>
        </div>

        <div className="home-actions">
          <Card className="action-card">
            <h2>Criar Sala</h2>
            <p>Comece uma nova sessão e convide seus amigos</p>
            <Button onClick={() => navigate('/create')} fullWidth>
              Criar Sala
            </Button>
          </Card>

          <Card className="action-card">
            <h2>Entrar em Sala</h2>
            <p>Participe de uma sessão existente com o código</p>
            <Button
              onClick={() => navigate('/join')}
              variant="secondary"
              fullWidth
            >
              Entrar em Sala
            </Button>
          </Card>
        </div>

        <div className="home-features">
          <h3>Como funciona?</h3>
          <div className="features-grid">
            <div className="feature-item">
              <span className="feature-icon">1️⃣</span>
              <h4>Crie ou entre</h4>
              <p>O host cria a sala e compartilha o código</p>
            </div>
            <div className="feature-item">
              <span className="feature-icon">2️⃣</span>
              <h4>Sugiram filmes</h4>
              <p>Todos podem adicionar suas sugestões</p>
            </div>
            <div className="feature-item">
              <span className="feature-icon">3️⃣</span>
              <h4>Sorteio justo</h4>
              <p>O sistema escolhe aleatoriamente o vencedor</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// angular-frontend/src/app/components/home/home.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class Home implements OnInit { 
  private router = inject(Router);
  private authService = inject(AuthService);

  currentUser: any = null;

  ngOnInit(): void {
    this.currentUser = this.authService.getCurrentUser();
  }

  goToCreateRoom(): void {
    this.router.navigate(['/rooms/create']);
  }

  goToJoinRoom(): void {
    this.router.navigate(['/rooms/join']);
  }

  logout(): void {
    this.authService.logout();
  }
}
<div class="home-container">
  <header class="home-header">
    <h1>🎬 Movie Night</h1>
    <div class="user-info">
      <span>Olá, <strong>{{ currentUser?.displayName }}</strong>!</span>
      <button class="btn-logout" (click)="logout()">Sair</button>
    </div>
  </header>

  <main class="home-main">
    <div class="home-content">
      <h2>Escolha uma opção</h2>
      <p>Crie uma nova sala ou entre em uma existente</p>

      <div class="action-cards">
        <div class="action-card" (click)="goToCreateRoom()">
          <div class="card-icon">➕</div>
          <h3>Criar Sala</h3>
          <p>Crie uma nova sala e convide seus amigos</p>
        </div>

        <div class="action-card" (click)="goToJoinRoom()">
          <div class="card-icon">🚪</div>
          <h3>Entrar em Sala</h3>
          <p>Entre em uma sala existente com o código</p>
        </div>
      </div>
    </div>
  </main>
</div>
