// frontend/src/pages/Room.tsx
import { useState, useEffect, FormEvent } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { roomService } from '../services/roomService';
import { Button } from '../components/ui/Button';
import { Input } from '../components/ui/Input';
import { Card } from '../components/ui/Card';
import { Loading } from '../components/ui/Loading';
import { ErrorMessage } from '../components/ui/ErrorMessage';
import { TransferOwnershipModal } from '../components/TransferOwnershipModal';
import type { RoomDetails, Movie } from '../@types';
import './Room.css';

export function Room() {
  const { code } = useParams<{ code: string }>();
  const navigate = useNavigate();
  const { userRole, logout, updateToken } = useAuth();

  const [room, setRoom] = useState<RoomDetails | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  const [movieTitle, setMovieTitle] = useState('');
  const [movieYear, setMovieYear] = useState('');
  const [addingMovie, setAddingMovie] = useState(false);
  const [finishing, setFinishing] = useState(false);
  const [copied, setCopied] = useState(false);
  const [deletingMovieId, setDeletingMovieId] = useState<string | null>(null);
  
  const [showTransferModal, setShowTransferModal] = useState(false);
  const [transferring, setTransferring] = useState(false);

  const isHost = userRole === 'HOST';
  const isFinished = room?.room.status === 'FINISHED';
  const currentUserId = room?.currentUser?.id;

  async function fetchRoom(isPolling = false) {
    if (!code) return;

    try {
      if (!isPolling) {
        setLoading(true);
      }
      setError('');
      const response = await roomService.getRoom(code);
      setRoom(response.data);

      if (response.data.currentUser.role !== userRole) {
        console.log('Role mudou! Obtendo novo token...');
        try {
          const refreshResponse = await roomService.refreshToken();
          updateToken(refreshResponse.data.token, refreshResponse.data.role);
        } catch (refreshError) {
          console.error('Erro ao renovar token:', refreshError);
        }
      }
    } catch (err: any) {
      setError(err.response?.data?.error || 'Erro ao carregar sala');
    } finally {
      if (!isPolling) {
        setLoading(false);
      }
    }
  }

  useEffect(() => {
    fetchRoom(false);

    const interval = setInterval(() => {
      if (!isFinished) {
        fetchRoom(true);
      }
    }, 5000);

    return () => clearInterval(interval);
  }, [code, isFinished]);

  async function handleAddMovie(e: FormEvent) {
    e.preventDefault();
    if (!code || !movieTitle.trim()) return;

    try {
      setAddingMovie(true);
      await roomService.addMovie(
        code,
        movieTitle.trim(),
        movieYear ? parseInt(movieYear) : undefined
      );

      setMovieTitle('');
      setMovieYear('');

      await fetchRoom(true);
    } catch (err: any) {
      alert(err.response?.data?.error || 'Erro ao adicionar filme');
    } finally {
      setAddingMovie(false);
    }
  }

  async function handleDeleteMovie(movieId: string, movieTitle: string) {
    if (!code) return;

    const confirm = window.confirm(
      `Tem certeza que deseja deletar "${movieTitle}"?`
    );

    if (!confirm) return;

    try {
      setDeletingMovieId(movieId);
      await roomService.deleteMovie(code, movieId);
      await fetchRoom(true);
    } catch (err: any) {
      alert(err.response?.data?.error || 'Erro ao deletar filme');
    } finally {
      setDeletingMovieId(null);
    }
  }

  async function handleTransferOwnership(newHostId: string) {
    if (!code) return;

    try {
      setTransferring(true);
      const response = await roomService.transferOwnership(code, newHostId);
      
      setShowTransferModal(false);
      
      updateToken(response.data.oldHostToken, 'GUEST');
      
      await fetchRoom(false);
    } catch (err: any) {
      alert(err.response?.data?.error || 'Erro ao transferir sala');
    } finally {
      setTransferring(false);
    }
  }

  async function handleFinishRoom() {
    if (!code) return;

    const confirm = window.confirm(
      'Tem certeza que deseja finalizar a sala e sortear o vencedor?'
    );

    if (!confirm) return;

    try {
      setFinishing(true);
      await roomService.finishRoom(code);
      await fetchRoom(false);
    } catch (err: any) {
      alert(err.response?.data?.error || 'Erro ao finalizar sala');
    } finally {
      setFinishing(false);
    }
  }

  async function handleCopyCode() {
    if (!room?.room.code) return;

    try {
      await navigator.clipboard.writeText(room.room.code);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      alert('Erro ao copiar código. Tente copiar manualmente.');
    }
  }

  function handleLeaveRoom() {
    logout();
    navigate('/');
  }

  function canDeleteMovie(movie: Movie): boolean {
    if (isHost) return true;
    return movie.suggestedBy.id === currentUserId;
  }

  const guests = room?.users?.filter(user => user.role === 'GUEST') || [];

  if (loading && !room) {
    return <Loading message="Carregando sala..." />;
  }

  if (error) {
    return (
      <div className="room-error-container">
        <ErrorMessage message={error} onRetry={() => fetchRoom(false)} />
        <Button onClick={() => navigate('/')} variant="secondary">
          Voltar ao início
        </Button>
      </div>
    );
  }

  if (!room) {
    return null;
  }

  return (
    <div className="room-container">
      <div className="room-content">
        <div className="room-header">
          <div className="room-header-info">
            <h1 className="room-title">
              {isFinished ? '🏆 Sala Finalizada' : '🎬 Movie Night'}
            </h1>
            <div className="room-code">
              <span>Código:</span>
              <strong>{room.room.code}</strong>
              <button
                onClick={handleCopyCode}
                className="copy-button"
                title="Copiar código"
              >
                {copied ? '✓' : '📋'}
              </button>
              {copied && <span className="copied-feedback">Copiado!</span>}
            </div>
          </div>
          <Button onClick={handleLeaveRoom} variant="danger">
            Sair
          </Button>
        </div>

        {isFinished && room.room.winnerMovie && (
          <Card className="winner-card">
            <h2 className="winner-title">🎉 Filme Vencedor!</h2>
            <div className="winner-movie">
              <h3>{room.room.winnerMovie.title}</h3>
              {room.room.winnerMovie.year && <p>({room.room.winnerMovie.year})</p>}
              <p className="winner-suggested">
                Sugerido por: {room.room.winnerMovie.suggestedBy.displayName}
              </p>
            </div>
          </Card>
        )}

        <div className="room-grid">
          {!isFinished && (
            <Card className="add-movie-card">
              <h2>Adicionar Filme</h2>
              <form onSubmit={handleAddMovie} className="add-movie-form">
                <Input
                  label="Título do filme"
                  type="text"
                  placeholder="Ex: Matrix"
                  value={movieTitle}
                  onChange={(e) => setMovieTitle(e.target.value)}
                  disabled={addingMovie}
                  required
                />
                <Input
                  label="Ano (opcional)"
                  type="number"
                  placeholder="Ex: 1999"
                  value={movieYear}
                  onChange={(e) => setMovieYear(e.target.value)}
                  disabled={addingMovie}
                  min="1900"
                  max={new Date().getFullYear() + 5}
                />
                <Button type="submit" fullWidth disabled={addingMovie}>
                  {addingMovie ? 'Adicionando...' : '+ Adicionar'}
                </Button>
              </form>
            </Card>
          )}

          <Card className="movies-card">
            <h2>
              Filmes Sugeridos ({room?.movies?.length || 0})
            </h2>
            {!room?.movies || room.movies.length === 0 ? (
              <p className="no-movies">Nenhum filme adicionado ainda</p>
            ) : (
              <ul className="movies-list">
                {room.movies.map((movie) => (
                  <li key={movie.id} className="movie-item">
                    <div className="movie-info">
                      <strong>{movie.title}</strong>
                      {movie.year && <span className="movie-year">({movie.year})</span>}
                    </div>
                    <div className="movie-actions">
                      <span className="movie-suggested-by">
                        por {movie.suggestedBy.displayName}
                      </span>
                      {!isFinished && canDeleteMovie(movie) && (
                        <button
                          onClick={() => handleDeleteMovie(movie.id, movie.title)}
                          className="delete-movie-button"
                          disabled={deletingMovieId === movie.id}
                          title="Deletar filme"
                        >
                          {deletingMovieId === movie.id ? '⏳' : '🗑️'}
                        </button>
                      )}
                    </div>
                  </li>
                ))}
              </ul>
            )}
          </Card>

          <Card className="users-card">
            <h2>Participantes ({room?.users?.length || 0})</h2>
            <ul className="users-list">
              {room?.users?.map((user) => (
                <li key={user.id} className="user-item">
                  <span className="user-info">
                    {user.id === currentUserId && (
                      <span className="user-indicator" title="Você">●</span>
                    )}
                    <span className="user-name">
                      {user.displayName}
                      {user.role === 'HOST' && ' 👑'}
                    </span>
                  </span>
                </li>
              ))}
            </ul>
          </Card>
        </div>

        {isHost && !isFinished && (
          <div className="room-footer">
            <div className="room-footer-actions">
              <Button
                onClick={() => setShowTransferModal(true)}
                variant="secondary"
                disabled={guests.length === 0}
              >
                👑 Transferir Sala
              </Button>
              <Button
                onClick={handleFinishRoom}
                disabled={finishing || !room?.movies || room.movies.length === 0}
                fullWidth
              >
                {finishing
                  ? 'Finalizando...'
                  : '🎲 Finalizar e Sortear Vencedor'}
              </Button>
            </div>
            {(!room?.movies || room.movies.length === 0) && (
              <p className="finish-warning">
                Adicione pelo menos um filme antes de finalizar
              </p>
            )}
          </div>
        )}
      </div>

      {showTransferModal && (
        <TransferOwnershipModal
          guests={guests}
          onTransfer={handleTransferOwnership}
          onClose={() => setShowTransferModal(false)}
          isTransferring={transferring}
        />
      )}
    </div>
  );
}

// angular-frontend/src/app/components/room/room.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { RoomService } from '../../services/room.service';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-room',
  templateUrl: './room.component.html',
  styleUrls: ['./room.component.css'],
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule]
})
export class RoomComponent implements OnInit, OnDestroy {
  roomCode: string = '';
  room: any = null;
  loading = true;
  error = '';
  
  movieForm!: FormGroup;
  addingMovie = false;
  finishing = false;
  deletingMovieId: string | null = null;
  
  private pollingSubscription?: Subscription;

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private formBuilder: FormBuilder,
    private roomService: RoomService
  ) {}

  ngOnInit(): void {
    this.roomCode = this.route.snapshot.params['code'];
    
    this.movieForm = this.formBuilder.group({
      title: ['', [Validators.required, Validators.minLength(2)]],
      year: ['', [Validators.min(1900), Validators.max(2030)]]
    });

    this.startPolling();
  }

  ngOnDestroy(): void {
    this.stopPolling();
  }

  get f() {
    return this.movieForm.controls;
  }

  get isHost(): boolean {
    return this.room?.currentUser?.role === 'HOST';
  }

  get isFinished(): boolean {
    return this.room?.room?.status === 'FINISHED';
  }

  startPolling(): void {
    this.pollingSubscription = this.roomService.getRoomWithPolling(this.roomCode).subscribe({
      next: (response) => {
        this.room = response.data;
        this.loading = false;
        this.error = '';
      },
      error: (error) => {
        console.error('Erro ao buscar sala:', error);
        this.error = 'Erro ao carregar sala';
        this.loading = false;
      }
    });
  }

  stopPolling(): void {
    if (this.pollingSubscription) {
      this.pollingSubscription.unsubscribe();
    }
  }

  onAddMovie(): void {
    if (this.movieForm.invalid) {
      return;
    }

    this.addingMovie = true;
    const { title, year } = this.movieForm.value;

    this.roomService.addMovie(this.roomCode, title, year || undefined).subscribe({
      next: (response) => {
        console.log('Filme adicionado:', response);
        this.movieForm.reset();
        this.addingMovie = false;
      },
      error: (error) => {
        console.error('Erro ao adicionar filme:', error);
        alert('Erro ao adicionar filme');
        this.addingMovie = false;
      }
    });
  }

  onDeleteMovie(movieId: string): void {
    if (!confirm('Deseja realmente remover este filme?')) {
      return;
    }

    this.deletingMovieId = movieId;

    this.roomService.deleteMovie(this.roomCode, movieId).subscribe({
      next: () => {
        console.log('Filme removido');
        this.deletingMovieId = null;
      },
      error: (error) => {
        console.error('Erro ao remover filme:', error);
        alert('Erro ao remover filme');
        this.deletingMovieId = null;
      }
    });
  }

  onFinishRoom(): void {
    if (!confirm('Deseja finalizar a sala e sortear o filme vencedor?')) {
      return;
    }

    this.finishing = true;

    this.roomService.finishRoom(this.roomCode).subscribe({
      next: (response) => {
        console.log('Sala finalizada:', response);
        this.finishing = false;
      },
      error: (error) => {
        console.error('Erro ao finalizar sala:', error);
        alert(error.error?.error || 'Erro ao finalizar sala');
        this.finishing = false;
      }
    });
  }

  copyRoomCode(): void {
    navigator.clipboard.writeText(this.roomCode).then(() => {
      alert('Código copiado!');
    });
  }

  leaveRoom(): void {
    if (confirm('Deseja realmente sair da sala?')) {
      this.router.navigate(['/home']);
    }
  }
}
<div class="room-container">
  <!-- Loading -->
  <div *ngIf="loading" class="loading-container">
    <div class="spinner-large"></div>
    <p>Carregando sala...</p>
  </div>

  <!-- Error -->
  <div *ngIf="error && !loading" class="error-container">
    <h2>❌ Erro</h2>
    <p>{{ error }}</p>
    <button class="btn btn-primary" (click)="leaveRoom()">Voltar</button>
  </div>

  <!-- Room Content -->
  <div *ngIf="!loading && !error && room" class="room-content">
    
    <!-- Header -->
    <header class="room-header">
      <div class="header-left">
        <h1>🎬 {{ room.room.code }}</h1>
        <button class="btn-copy" (click)="copyRoomCode()" title="Copiar código">
          📋
        </button>
      </div>
      <button class="btn-leave" (click)="leaveRoom()">Sair</button>
    </header>

    <!-- Winner (if finished) -->
    <div *ngIf="isFinished && room.room.winnerMovie" class="winner-section">
      <div class="winner-card">
        <div class="winner-icon">🏆</div>
        <h2>Filme Vencedor!</h2>
        <h3>{{ room.room.winnerMovie.title }}</h3>
        <p *ngIf="room.room.winnerMovie.year">({{ room.room.winnerMovie.year }})</p>
        <p class="suggested-by">
          Sugerido por: <strong>{{ room.room.winnerMovie.suggestedBy.displayName }}</strong>
        </p>
      </div>
    </div>

    <div class="room-main">
      <!-- Left Column: Movies -->
      <div class="room-section movies-section">
        <h2>🍿 Filmes Sugeridos ({{ room.movies.length }})</h2>

        <!-- Add Movie Form (only if not finished) -->
        <div *ngIf="!isFinished" class="add-movie-form">
          <form [formGroup]="movieForm" (ngSubmit)="onAddMovie()">
            <div class="form-row">
              <input
                type="text"
                formControlName="title"
                class="form-control"
                placeholder="Nome do filme"
                [disabled]="addingMovie"
              />
              <input
                type="number"
                formControlName="year"
                class="form-control year-input"
                placeholder="Ano"
                [disabled]="addingMovie"
              />
              <button
                type="submit"
                class="btn btn-add"
                [disabled]="addingMovie || movieForm.invalid"
              >
                <span *ngIf="!addingMovie">➕</span>
                <span *ngIf="addingMovie" class="spinner-small"></span>
              </button>
            </div>
          </form>
        </div>

        <!-- Movies List -->
        <div class="movies-list">
          <div *ngIf="room.movies.length === 0" class="empty-state">
            <p>Nenhum filme sugerido ainda</p>
            <p class="hint">Seja o primeiro a adicionar! 🎬</p>
          </div>

          <div
            *ngFor="let movie of room.movies"
            class="movie-card"
            [class.deleting]="deletingMovieId === movie.id"
          >
            <div class="movie-info">
              <h4>{{ movie.title }}</h4>
              <p *ngIf="movie.year" class="movie-year">{{ movie.year }}</p>
              <p class="movie-author">por {{ movie.suggestedBy.displayName }}</p>
            </div>
            <button
              *ngIf="!isFinished && (isHost || movie.suggestedBy.id === room.currentUser.id)"
              class="btn-delete"
              (click)="onDeleteMovie(movie.id)"
              [disabled]="deletingMovieId === movie.id"
            >
              🗑️
            </button>
          </div>
        </div>

        <!-- Finish Button (only host) -->
        <button
          *ngIf="!isFinished && isHost && room.movies.length > 0"
          class="btn btn-finish"
          (click)="onFinishRoom()"
          [disabled]="finishing"
        >
          <span *ngIf="!finishing">🎲 Sortear Vencedor</span>
          <span *ngIf="finishing">
            <span class="spinner-small"></span> Sorteando...
          </span>
        </button>
      </div>

      <!-- Right Column: Participants -->
      <div class="room-section participants-section">
        <h2>👥 Participantes ({{ room.users.length }})</h2>
        
        <div class="participants-list">
          <div
            *ngFor="let user of room.users"
            class="participant-card"
            [class.is-host]="user.role === 'HOST'"
            [class.is-you]="user.id === room.currentUser.id"
          >
            <div class="participant-avatar">
              {{ user.displayName.charAt(0).toUpperCase() }}
            </div>
            <div class="participant-info">
              <span class="participant-name">
                {{ user.displayName }}
                <span *ngIf="user.id === room.currentUser.id" class="badge-you">você</span>
              </span>
              <span *ngIf="user.role === 'HOST'" class="badge-host">👑 Host</span>
            </div>
          </div>
        </div>

        <div class="room-info">
          <p><strong>Status:</strong> {{ isFinished ? '✅ Finalizada' : '🟢 Ativa' }}</p>
          <p><strong>Código:</strong> {{ room.room.code }}</p>
        </div>
      </div>
    </div>

  </div>
</div>
