// angular-frontend/src/app/components/create-room/create-room.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { RoomService } from '../../services/room.service';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-create-room',
  templateUrl: './create-room.component.html',
  styleUrls: ['./create-room.component.css'],
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule]
})
export class CreateRoomComponent implements OnInit {
  createForm!: FormGroup;
  loading = false;
  errorMessage = '';

  constructor(
    private formBuilder: FormBuilder,
    private roomService: RoomService,
    private authService: AuthService,
    private router: Router
  ) {}

  ngOnInit(): void {
    const currentUser = this.authService.getCurrentUser();
    
    this.createForm = this.formBuilder.group({
      hostName: [currentUser?.displayName || '', [Validators.required, Validators.minLength(3)]]
    });
  }

  get f() {
    return this.createForm.controls;
  }

  onSubmit(): void {
    this.errorMessage = '';

    if (this.createForm.invalid) {
      this.errorMessage = 'Por favor, preencha seu nome.';
      return;
    }

    this.loading = true;

    this.roomService.createRoom(this.createForm.value.hostName).subscribe({
      next: (response) => {
        console.log('Sala criada:', response);
        const roomCode = response.data.room.code;
        
        // Atualizar token se necessário
        if (response.data.token) {
          this.authService.updateToken(response.data.token, response.data.hostUser.role);
        }
        
        this.router.navigate(['/rooms', roomCode]);
      },
      error: (error) => {
        console.error('Erro ao criar sala:', error);
        this.errorMessage = error.error?.error || 'Erro ao criar sala';
        this.loading = false;
      }
    });
  }

  goBack(): void {
    this.router.navigate(['/home']);
  }
}
<div class="create-room-container">
  <div class="create-room-card">
    <h1>Criar Nova Sala</h1>
    <p class="subtitle">Digite seu nome para criar uma sessão</p>

    <form [formGroup]="createForm" (ngSubmit)="onSubmit()" class="create-room-form">
      <div class="form-group">
        <label for="hostName">Seu nome</label>
        <input
          type="text"
          id="hostName"
          formControlName="hostName"
          class="form-control"
          [class.is-invalid]="f['hostName'].invalid && f['hostName'].touched"
          placeholder="Ex: João"
          autocomplete="name"
        />
        <div class="invalid-feedback" *ngIf="f['hostName'].invalid && f['hostName'].touched">
          <span *ngIf="f['hostName'].errors?.['required']">Nome é obrigatório</span>
          <span *ngIf="f['hostName'].errors?.['minlength']">Nome deve ter no mínimo 3 caracteres</span>
        </div>
      </div>

      <div class="alert alert-danger" *ngIf="errorMessage">
        {{ errorMessage }}
      </div>

      <button
        type="submit"
        class="btn btn-primary btn-block"
        [disabled]="loading || createForm.invalid"
      >
        <span *ngIf="!loading">Criar Sala</span>
        <span *ngIf="loading">
          <span class="spinner"></span> Criando...
        </span>
      </button>

      <button
        type="button"
        class="btn btn-secondary btn-block"
        (click)="goBack()"
        [disabled]="loading"
      >
        Voltar
      </button>
    </form>
  </div>
</div>

// frontend/src/pages/CreateRoom.tsx
import { useState, FormEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { roomService } from '../services/roomService';
import { Button } from '../components/ui/Button';
import { Input } from '../components/ui/Input';
import { Card } from '../components/ui/Card';
import './CreateRoom.css';

export function CreateRoom() {
  const [hostName, setHostName] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const navigate = useNavigate();
  const { login } = useAuth();

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();
    setError('');

    if (!hostName.trim()) {
      setError('Digite seu nome');
      return;
    }

    try {
      setLoading(true);
      const response = await roomService.createRoom(hostName.trim());

      const { token, room, hostUser } = response.data;

      // Salvar autenticação
      login(token, room.code, hostUser.role);

      // Redirecionar para a sala
      navigate(`/room/${room.code}`);
    } catch (err: any) {
      setError(err.response?.data?.error || 'Erro ao criar sala');
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="create-room-container">
      <Card className="create-room-card">
        <h1 className="create-room-title">Criar Sala</h1>
        <p className="create-room-description">
          Digite seu nome para criar uma nova sessão
        </p>

        <form onSubmit={handleSubmit} className="create-room-form">
          <Input
            label="Seu nome"
            type="text"
            placeholder="Ex: João"
            value={hostName}
            onChange={(e) => setHostName(e.target.value)}
            error={error}
            disabled={loading}
            autoFocus
          />

          <Button type="submit" fullWidth disabled={loading}>
            {loading ? 'Criando...' : 'Criar Sala'}
          </Button>

          <Button
            type="button"
            variant="secondary"
            fullWidth
            onClick={() => navigate('/')}
            disabled={loading}
          >
            Voltar
          </Button>
        </form>
      </Card>
    </div>
  );
}
