// angular-frontend/src/app/components/join-room/join-room.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { RoomService } from '../../services/room.service';
import { AuthService } from '../../services/auth.service';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-join-room',
  templateUrl: './join-room.component.html',
  styleUrls: ['./join-room.component.css'],
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule]
})
export class JoinRoom implements OnInit {
  private formBuilder = inject(FormBuilder);
  private roomService = inject(RoomService);
  private authService = inject(AuthService);
  private router = inject(Router);

  joinForm!: FormGroup;
  loading = false;
  errorMessage = '';

  ngOnInit(): void {
    const currentUser = this.authService.getCurrentUser();
    
    this.joinForm = this.formBuilder.group({
      roomCode: ['', [Validators.required, Validators.minLength(5), Validators.maxLength(5)]],
      displayName: [currentUser?.displayName || '', [Validators.required, Validators.minLength(3)]]
    });
  }

  get f() {
    return this.joinForm.controls;
  }

  onSubmit(): void {
    this.errorMessage = '';

    if (this.joinForm.invalid) {
      this.errorMessage = 'Por favor, preencha todos os campos corretamente.';
      return;
    }

    this.loading = true;

    const { roomCode, displayName } = this.joinForm.value;

    this.roomService.joinRoom(roomCode.toUpperCase(), displayName).subscribe({
      next: (response) => {
        console.log('Entrou na sala:', response);
        
        if (response.data.token) {
          this.authService.updateToken(response.data.token, response.data.user.role);
        }
        
        this.router.navigate(['/rooms', roomCode.toUpperCase()]);
      },
      error: (error) => {
        console.error('Erro ao entrar na sala:', error);
        this.errorMessage = error.error?.error || 'Sala não encontrada ou código inválido';
        this.loading = false;
      }
    });
  }

  goBack(): void {
    this.router.navigate(['/home']);
  }

  onRoomCodeInput(event: any): void {
    const value = event.target.value.toUpperCase();
    this.joinForm.patchValue({ roomCode: value });
  }
}
<div class="join-room-container">
  <div class="join-room-card">
    <h1>Entrar em Sala</h1>
    <p class="subtitle">Digite o código da sala e seu nome para participar</p>

    <form [formGroup]="joinForm" (ngSubmit)="onSubmit()" class="join-room-form">
      <div class="form-group">
        <label for="roomCode">Código da sala</label>
        <input
          type="text"
          id="roomCode"
          formControlName="roomCode"
          (input)="onRoomCodeInput($event)"
          class="form-control code-input"
          [class.is-invalid]="f['roomCode'].invalid && f['roomCode'].touched"
          placeholder="Ex: ABC12"
          maxlength="5"
          autocomplete="off"
        />
        <div class="invalid-feedback" *ngIf="f['roomCode'].invalid && f['roomCode'].touched">
          <span *ngIf="f['roomCode'].errors?.['required']">Código é obrigatório</span>
          <span *ngIf="f['roomCode'].errors?.['minlength'] || f['roomCode'].errors?.['maxlength']">
            Código deve ter exatamente 5 caracteres
          </span>
        </div>
      </div>

      <div class="form-group">
        <label for="displayName">Seu nome</label>
        <input
          type="text"
          id="displayName"
          formControlName="displayName"
          class="form-control"
          [class.is-invalid]="f['displayName'].invalid && f['displayName'].touched"
          placeholder="Ex: Maria"
          autocomplete="name"
        />
        <div class="invalid-feedback" *ngIf="f['displayName'].invalid && f['displayName'].touched">
          <span *ngIf="f['displayName'].errors?.['required']">Nome é obrigatório</span>
          <span *ngIf="f['displayName'].errors?.['minlength']">Nome deve ter no mínimo 3 caracteres</span>
        </div>
      </div>

      <div class="alert alert-danger" *ngIf="errorMessage">
        {{ errorMessage }}
      </div>

      <button
        type="submit"
        class="btn btn-primary btn-block"
        [disabled]="loading || joinForm.invalid"
      >
        <span *ngIf="!loading">Entrar na Sala</span>
        <span *ngIf="loading">
          <span class="spinner"></span> Entrando...
        </span>
      </button>

      <button
        type="button"
        class="btn btn-secondary btn-block"
        (click)="goBack()"
        [disabled]="loading"
      >
        Voltar
      </button>
    </form>
  </div>
</div>

// frontend/src/pages/JoinRoom.tsx
import { useState, FormEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { roomService } from '../services/roomService';
import { Button } from '../components/ui/Button';
import { Input } from '../components/ui/Input';
import { Card } from '../components/ui/Card';
import './JoinRoom.css';

export function JoinRoom() {
  const [roomCode, setRoomCode] = useState('');
  const [displayName, setDisplayName] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const navigate = useNavigate();
  const { login } = useAuth();

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();
    setError('');

    if (!roomCode.trim()) {
      setError('Digite o código da sala');
      return;
    }

    if (!displayName.trim()) {
      setError('Digite seu nome');
      return;
    }

    try {
      setLoading(true);
  
      const response = await roomService.joinRoom(
       roomCode.trim().toUpperCase(),
       displayName.trim()
      );

      console.log('✅ Resposta:', response);

      const { token, room, user } = response.data;

      // Salvar autenticação
      login(token, room.code, user.role);

      navigate(`/room/${room.code}`);
    } catch (err: any) {
      console.error('❌ Erro:', err);
      setError(err.response?.data?.error || 'Erro ao entrar na sala');
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="join-room-container">
      <Card className="join-room-card">
        <h1 className="join-room-title">Entrar em Sala</h1>
        <p className="join-room-description">
          Digite o código da sala e seu nome para participar
        </p>

        <form onSubmit={handleSubmit} className="join-room-form">
          <Input
            label="Código da sala"
            type="text"
            placeholder="Ex: AB3D5"
            value={roomCode}
            onChange={(e) => setRoomCode(e.target.value.toUpperCase())}
            maxLength={5}
            disabled={loading}
            autoFocus
          />

          <Input
            label="Seu nome"
            type="text"
            placeholder="Ex: Maria"
            value={displayName}
            onChange={(e) => setDisplayName(e.target.value)}
            disabled={loading}
          />

          {error && <p className="join-room-error">{error}</p>}

          <Button type="submit" fullWidth disabled={loading}>
            {loading ? 'Entrando...' : 'Entrar na Sala'}
          </Button>

          <Button
            type="button"
            variant="secondary"
            fullWidth
            onClick={() => navigate('/')}
            disabled={loading}
          >
            Voltar
          </Button>
        </form>
      </Card>
    </div>
  );
}
